apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapi
  labels:
    app: movieapi
  annotations:
    kubernetes.io/change-cause: "connect with db postgresql (fixed)"
spec:
  selector:
    matchLabels:
      app: movieapi
  replicas: 3
  template:
    metadata:
      labels:
        app: movieapi
    spec:
      containers:
      - name: movieapi
        image: movieapi:1.0
        ports:
        - containerPort: 8080
        env:
        # - name: DB_CREATE_TABLES
        #   value: "false"   # default value
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_URL
          value: "postgresql+psycopg2://$(DB_USER):$(DB_PASSWORD)@dbmovie-0.dbmovie:5432/$(DB_NAME)"

